# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
import plot_file
from time import sleep
import sys
import pandas as pd
from PyQt5.QtWidgets import QMainWindow


class WorkThread(QThread):
    # 成员属性
    my_data = None

    time_arr = None
    scc_deg_ref_steering_angel_arr = None
    acc_veh_dyn_yaw_rate_raw_arr = None
    scc_hands_off_count_arr = None
    scc_lane_model_lane_width_cross_point_arr = None
    scc_das_lka_state_arr = None

    # 初始化线程
    def __int__(self):
        super(WorkThread, self).__init__()

    def get_data(self):
        # 获取希望得到的数据
        file_name = plot_file.FileProcess().get_file()
        df = pd.read_excel(file_name)
        self.time_arr = df.loc[:, "t[s]"].tolist()
        self.scc_deg_ref_steering_angel_arr = df.loc[:, "SCC_degRefSteeringAngel_mp[]"].tolist()
        self.acc_veh_dyn_yaw_rate_raw_arr = df.loc[:, "ACC_VehDynYawRateRaw_MP[]"].tolist()
        self.scc_hands_off_count_arr = df.loc[:, "SCC_HandsOffCount_mp[]"].tolist()
        self.scc_lane_model_lane_width_cross_point_arr = df.loc[:, "SCC_LaneModel_LaneWidth_CrossPoint_mp[]"].tolist()
        self.scc_das_lka_state_arr = df.loc[:, "SCC_DASLKAState_mp[]"].tolist()

    # 线程运行函数
    def run(self):
        for i in range(len(self.time_arr) - 1):
            global time, scc_deg_ref_steering_angel, acc_veh_dyn_yaw_rate_raw, scc_hands_off_count,\
                scc_lane_model_lane_width_cross_point, scc_das_lka_state
            time = self.time_arr[i]
            scc_deg_ref_steering_angel = self.scc_deg_ref_steering_angel_arr[i]
            acc_veh_dyn_yaw_rate_raw = self.acc_veh_dyn_yaw_rate_raw_arr[i]
            scc_hands_off_count= self.scc_hands_off_count_arr[i]
            scc_lane_model_lane_width_cross_point = self.scc_lane_model_lane_width_cross_point_arr[i]
            scc_das_lka_state = self.scc_das_lka_state_arr[i]
            sleep(self.time_arr[i+1] - self.time_arr[i])


class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.Mytimer()
        pass

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 510)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 70, 411, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 707, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "可视化工具1.0"))
        self.label_2.setText(_translate("MainWindow", "可视化工具"))
        self.label.setText(_translate("MainWindow", "SCC_degRefSteeringAngel_mp"))
        self.label_3.setText(_translate("MainWindow", "ACC_VehDynYawRateRaw_mp"))
        self.label_4.setText(_translate("MainWindow", "SCC_HandsOffCount_mp"))
        self.label_5.setText(_translate("MainWindow", "SCC_LaneModel_LaneWidth_CrossPoint_mp"))
        self.label_6.setText(_translate("MainWindow", "SCC_DASLKAState_mp"))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.pushButton.setText(_translate("MainWindow", "暂停"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

    # 定义定时器，使用定时器每隔一段时间来出发update函数，从而刷新数据
    def Mytimer(self):
        timer = QTimer(self)
        timer.timeout.connect(self.update)
        timer.start(100)

    # 刷新函数
    def update(self):
        self.lineEdit.setText(str(scc_deg_ref_steering_angel))
        self.lineEdit_2.setText(str(acc_veh_dyn_yaw_rate_raw))
        self.lineEdit_3.setText(str(scc_hands_off_count))
        self.lineEdit_4.setText(str(scc_lane_model_lane_width_cross_point))
        self.lineEdit_9.setText(str(scc_das_lka_state))


def mainwindows():
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    workThread = WorkThread()
    workThread.get_data()
    workThread.start()
    mainwindows()
